package ntuproj;
// Generated Apr 10, 2013 10:18:17 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * Claims generated by hbm2java
 */
public class Claims  implements java.io.Serializable {


     private Integer claimid;
     private int empid;
     private String mgrname;
     private Integer overtimehours;
     private Date startdate;
     private Date enddate;
     private String comments;
     private String status;

    public Claims() {
    }

	
    public Claims(int empid) {
        this.empid = empid;
    }
    public Claims(int empid, String mgrname, Integer overtimehours, Date startdate, Date enddate, String comments, String status) {
       this.empid = empid;
       this.mgrname = mgrname;
       this.overtimehours = overtimehours;
       this.startdate = startdate;
       this.enddate = enddate;
       this.comments = comments;
       this.status = status;
    }
   
    public Integer getClaimid() {
        return this.claimid;
    }
    
    public void setClaimid(Integer claimid) {
        this.claimid = claimid;
    }
    public int getEmpid() {
        return this.empid;
    }
    
    public void setEmpid(int empid) {
        this.empid = empid;
    }
    public String getMgrname() {
        return this.mgrname;
    }
    
    public void setMgrname(String mgrname) {
        this.mgrname = mgrname;
    }
    public Integer getOvertimehours() {
        return this.overtimehours;
    }
    
    public void setOvertimehours(Integer overtimehours) {
        this.overtimehours = overtimehours;
    }
    public Date getStartdate() {
        return this.startdate;
    }
    
    public void setStartdate(Date startdate) {
        this.startdate = startdate;
    }
    public Date getEnddate() {
        return this.enddate;
    }
    
    public void setEnddate(Date enddate) {
        this.enddate = enddate;
    }
    public String getComments() {
        return this.comments;
    }
    
    public void setComments(String comments) {
        this.comments = comments;
    }
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }




}


