package ntuproj;
// Generated Apr 10, 2013 10:18:17 PM by Hibernate Tools 3.2.1.GA



/**
 * Employee generated by hbm2java
 */
public class Employee  implements java.io.Serializable {


     private int empid;
     private String fname;
     private String lnameame;
     private String email;
     private String password;
     private Integer emptype;

    public Employee() {
    }

	
    public Employee(int empid, String email, String password) {
        this.empid = empid;
        this.email = email;
        this.password = password;
    }
    public Employee(int empid, String fname, String lnameame, String email, String password, Integer emptype) {
       this.empid = empid;
       this.fname = fname;
       this.lnameame = lnameame;
       this.email = email;
       this.password = password;
       this.emptype = emptype;
    }
   
    public int getEmpid() {
        return this.empid;
    }
    
    public void setEmpid(int empid) {
        this.empid = empid;
    }
    public String getFname() {
        return this.fname;
    }
    
    public void setFname(String fname) {
        this.fname = fname;
    }
    public String getLnameame() {
        return this.lnameame;
    }
    
    public void setLnameame(String lnameame) {
        this.lnameame = lnameame;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public Integer getEmptype() {
        return this.emptype;
    }
    
    public void setEmptype(Integer emptype) {
        this.emptype = emptype;
    }




}


